connection: postgres://postgres:123456@localhost:5432/app
test:
  account:
    accountId: 1fb6e901-f4de-4653-80e7-07c207073f61
    name: A B
    email: a@b.com
    document: '87465849004'
    password: 123ABCdef
  asset:
    usd:
      id: 1c3d068e-c326-4ad1-9246-df2b84c393db
      ticker: USD
    btc:
      id: 9b9174a1-17ce-423e-9fef-0aa1dbd314de
      ticker: BTC
